M48
; DRILL file {KiCad 8.0.0-8.0.0-1~ubuntu20.04.1} date 2024-06-18T17:36:14-0600
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-06-18T17:36:14-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.0-8.0.0-1~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1299
%
G90
G05
T1
X7.1976Y-0.9598
X7.5126Y-0.9598
T2
X6.0024Y-1.0122
X6.5024Y-1.0122
M30
